# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PiThing',
            new_name='LED',
        ),
        migrations.RenameField(
            model_name='led',
            old_name='pi_thing_text',
            new_name='led_text',
        ),
    ]
