# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_author_switch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Owner',
        ),
        migrations.AlterModelOptions(
            name='led',
            options={'permissions': (('on', 'can turn on LED'), ('off', 'can turn off LED'))},
        ),
        migrations.RenameField(
            model_name='led',
            old_name='led_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='switch_text',
            new_name='name',
        ),
    ]
