# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20170627_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='led',
            options={'permissions': (('led_on', 'can turn on LED'), ('led_off', 'can turn off LED'), ('led_view', 'can view LED state'))},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'permissions': (('read', 'can read Switch'),)},
        ),
    ]
