# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20170704_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='name',
        ),
    ]
