# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_switch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
