# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=20),
        ),
    ]
