# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20170714_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='led',
            options={'permissions': (('led_on', 'can turn on LED'), ('led_off', 'can turn off LED'), ('led_view', 'can view LED state'), ('nfc_feat', 'nfc security feature'))},
        ),
    ]
