# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_auto_20170714_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='uid',
        ),
        migrations.AddField(
            model_name='person',
            name='keys',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
