# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_remove_publisher_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
