# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_publisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='sessionID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
