# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_publisher_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='id',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='publisher', max_length=200, primary_key=True, serialize=False),
        ),
    ]
