# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20170724_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='pin_offset',
            field=models.IntegerField(null=True),
        ),
    ]
